require_relative 'piece'
require_relative 'nullpiece'
require_relative 'king'
require_relative 'pawn'
require_relative 'bishop'
require_relative 'rook'
require_relative 'queen'
require_relative 'knight'
