# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecfa6500d93ffd77a927523471f19089c802a53b3f13706d3a46cc7e0644dc53725542448f82082d7193411d96a2378fd70320a2129cfcc78a798b3ae1d25d0f

test:
  secret_key_base: 38f60f4c2798456b5ad52c486ba19722c6ff127fec43279ffad1cfca37e520c7ec68aec2ee1c876a485c423ac7a4f3cc08ade83effb52fd291b372d6d79c13f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
